name: Dispatch Update Submodule
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Dispatch update to Git Blog Project
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: yokikim/blog
          event-type: update-submodule
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
